services:
  app:
    image: mcr.microsoft.com/devcontainers/javascript-node:1-20-bookworm
    volumes:
      - ../..:/workspaces:cached
    command: sleep infinity
    network_mode: service:db

  db:
    image: mongo:7
    restart: unless-stopped
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
