import { useState } from 'react';
import { AlertCircle, Loader2, Sparkles } from 'lucide-react';
import { research } from '../lib/api';
import type { ResearchReport } from '../types';

export default function ThesisCard({ data }: { data: ResearchReport }) {
  const [text, setText] = useState<string | null>(null);
  const [model, setModel] = useState<string>('');
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState<string | null>(null);

  async function generate() {
    setLoading(true);
    setError(null);
    try {
      const r = await research.thesis(data.ticker);
      setText(r.text);
      setModel(r.model);
    } catch (err: any) {
      setError(err?.response?.data?.error || 'Could not generate thesis.');
    } finally {
      setLoading(false);
    }
  }

  return (
    <div
      className="rounded-3xl p-7 animate-fadeUp animate-delay-9"
      style={{ background: 'color-mix(in srgb, var(--amber) 8%, var(--surface))' }}
    >
      <div className="flex items-start justify-between gap-4 mb-4">
        <div>
          <div className="flex items-center gap-1.5 mb-1">
            <Sparkles size={13} className="text-amber" />
            <span className="eyebrow text-amber">AI thesis</span>
          </div>
          <h3 className="section-title">Read between the numbers</h3>
        </div>
        {!text && (
          <button
            onClick={generate}
            disabled={loading}
            className="btn-primary text-sm disabled:opacity-60"
          >
            {loading ? (
              <>
                <Loader2 size={14} className="animate-spin mr-1.5" /> Thinking…
              </>
            ) : (
              <>
                <Sparkles size={14} className="mr-1.5" /> Generate
              </>
            )}
          </button>
        )}
      </div>

      {error && (
        <div className="flex items-start gap-2 text-brick text-sm rounded-2xl px-4 py-3 mb-3"
          style={{ background: 'color-mix(in srgb, var(--brick) 10%, transparent)' }}
        >
          <AlertCircle size={16} className="mt-0.5 flex-shrink-0" />
          <span>{error}</span>
        </div>
      )}

      {text ? (
        <div className="space-y-4 text-[15px] leading-relaxed text-ink whitespace-pre-line">
          {text}
          <div className="hairline-divider mt-5 mb-3" />
          <div className="flex items-center justify-between text-[11px] text-ink-tertiary">
            <span>Generated by {model}.</span>
            <button onClick={generate} disabled={loading} className="hover:text-ink transition disabled:opacity-50">
              {loading ? 'Regenerating…' : 'Regenerate'}
            </button>
          </div>
        </div>
      ) : !error && !loading ? (
        <p className="text-ink-secondary text-[15px] leading-relaxed">
          Press <strong>Generate</strong> to get a plain-English three-paragraph thesis: why it's priced where it is,
          what would have to be true for it to outperform, and the most likely way the thesis breaks.
        </p>
      ) : null}
    </div>
  );
}
